FLASK_APP=microblog.py
FLASK_ENV=development
MAIL_SERVER = "server"
MAIL_PORT = 000
MAIL_USE_TLS = True
MAIL_USERNAME = "apikey"
MAIL_PASSWORD = "password"
MAIL_DEFAULT_SENDER = "example@example.com"
MAIL_API_KEY = "apikey"
ADMINS = ["example@example.com"]
